backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: article
    label: Article
    folder: content/articles
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }
      - { name: tags, label: Tags, widget: list }
